### ISSUE TITLE
Error building model; not modifying configuration

### ISSUE THREAD

**Issue by rimusz** [deis/router#62]
```
$ kubectl --namespace=deis logs deis-router-egcwv
2015/12/18 21:07:06 INFO: Starting nginx...
2015/12/18 21:07:06 INFO: nginx started.
2015/12/18 21:07:06 Error building model; not modifying configuration: Get https://10.100.0.1:443/api/v1/namespaces/deis/replicationcontrollers/deis-router: EOF.
2015/12/18 21:07:16 Error building model; not modifying configuration: Get https://10.100.0.1:443/api/v1/namespaces/deis/replicationcontrollers/deis-router: read tcp 10.244.33.8:54458->10.100.0.1:443: read: connection reset by peer.
2015/12/18 21:07:26 Error building model; not modifying configuration: Get https://10.100.0.1:443/api/v1/namespaces/deis/replicationcontrollers/deis-router: EOF.
2015/12/18 21:07:36 Error building model; not modifying configuration: Get https://10.100.0.1:443/api/v1/namespaces/deis/replicationcontrollers/deis-router: EOF.
2015/12/18 21:07:46 Error building model; not modifying configuration: Get https://10.100.0.1:443/api/v1/namespaces/deis/replicationcontrollers/deis-router: EOF.
2015/12/18 21:07:56 Error building model; not modifying configuration: Get https://10.100.0.1:443/api/v1/namespaces/deis/replicationcontrollers/deis-router: EOF.
2015/12/18 21:08:06 Error building model; not modifying configuration: Get https://10.100.0.1:443/api/v1/namespaces/deis/replicationcontrollers/deis-router: EOF.
```

**Comment by krancour** [comment]
This would appear to be a problem of connectivity to the k8s API.  If you `kubectl get deis-router-egcwv --namespace=deis -o yaml`, does it show a secret token mounted at `/var/run/secrets/kubernetes.io/serviceaccount`?

In the past, there were some circumstances where the token may have been missing.  Depending what the admission controls were in the cluster, the default service account for the Deis namespace may not have existed and neither would the secret token used by that service account.  We had accounted for that possibility by _explicitly_ creating and using a service account named `deis` in the `deis` namespace _before_ any rcs or other resources are created.

Maybe that's not working as we thought it would and the particular set of admission controls on kube-solo is exposing that?  I'm just hypothesizing.

**Comment by helgi** [comment]
Started seeing the same thing on `minio` under `micro-kube` - Probably the same issue

**Comment by krancour** [comment]
@helgi are you seeing this problem _just_ with minio on micro-kube?  Or with minio _and_ router?

**Comment by helgi** [comment]
Right now I'm seeing only `minio` - router is just pending because I'm using micro-kube and I can't seem to delete the old ingress :/

**Comment by krancour** [comment]
Yup... that was a problem on the master branch, but not in active-dev.  I fixed it tho... upgrade to the latest from master / v0.2.2

**Comment by rimusz** [comment]
@krancour still seeing the same issue, secret token is mounted at `/var/run/secrets/kubernetes.io/serviceaccount`

**Comment by krancour** [comment]
@rimusz, @jchauncey has been reporting an issue similar to this on kube-solo, while I've been unable to replicate this on the latest micro-kube.  I assume you're on kube-solo as well.  Do you know if there's anything in how it's set up that would interfere with the following line establishing a connection?

```
kubeClient, err := client.NewInCluster()
```

I believe `.NewInCluster()` makes assumptions about where the API is and how it's secured.

**Comment by rimusz** [comment]
@krancour, @jchauncey is using https://github.com/rimusz/coreos-osx-kubernetes-cluster, which is vagrant based k8s cluster on coreos. both apps  use very similar setup via fleet units with the go binaries

**Comment by krancour** [comment]
I'm trying to narrow down what might be wrong here...

Can both of you see a service named "kubernetes" in the default namespace?  Does that service have any endpoints?

```
[kent@mbp router]$ kubectl describe service kubernetes --namespace=default
Name:			kubernetes
Namespace:		default
Labels:			component=apiserver,provider=kubernetes
Selector:		<none>
Type:			ClusterIP
IP:			10.3.0.1
Port:			<unnamed>	443/TCP
Endpoints:		10.0.0.50:443
Session Affinity:	None
No events.
```

**Comment by jchauncey** [comment]
yeah its there its just not reachable from pods/hosts (usign the service ip) we believe its because the kubelet wasnt started with ` --configure-cbr0=true`

**Comment by rimusz** [comment]
it looks it is for sure something is wrong with SSL/certs setup, going to check the kube-solo and coreos-osx-kubernetes-cluster Apps setup

**Comment by rimusz** [comment]
found the problem: commenting out `--runtime_config=extensions/v1beta1=true,extensions/v1beta1/daemonsets=true` router works just fine:
```
$ kubectl --namespace=deis logs deis-router-wilo1
2015/12/29 17:01:01 INFO: Starting nginx...
2015/12/29 17:01:01 INFO: nginx started.
2015/12/29 17:01:01 INFO: Router configuration has changed in k8s.
2015/12/29 17:01:01 INFO: Reloading nginx...
2015/12/29 17:01:01 INFO: nginx reloaded.
2015/12/29 17:01:01 [notice] 14#0: signal process started
```

**Comment by jchauncey** [comment]
Wtf...

**Comment by rimusz** [comment]
indeed WTF :)

**Comment by rimusz** [comment]
so blame on @krancour haha

**Comment by rimusz** [comment]
long live my k8s Apps :)

**Comment by jchauncey** [comment]
Does that allow you to talk to the api server in a container?

**Comment by rimusz** [comment]
yep, via SSL:
```
curl -k https://10.100.0.1:443
Unauthorised
```

**Comment by rimusz** [comment]
enabled `runtime_config=extensions/v1beta1=true,extensions/v1beta1/daemonsets=true` in micro-kube:
```
$ kubectl --namespace=deis logs deis-router-lty4l
2015/12/29 17:49:00 INFO: Starting nginx...
2015/12/29 17:49:00 INFO: nginx started.
2015/12/29 17:49:00 Error building model; not modifying configuration: Get https://10.3.0.1:443/api/v1/namespaces/deis/replicationcontrollers/deis-router: x509: certificate is valid for 127.0.0.1, 192.168.64.2, not 10.3.0.1.
2015/12/29 17:49:10 Error building model; not modifying configuration: Get https://10.3.0.1:443/api/v1/namespaces/deis/replicationcontrollers/deis-router: x509: certificate is valid for 127.0.0.1, 192.168.64.2, not 10.3.0.1.
2015/12/29 17:49:20 Error building model; not modifying configuration: Get https://10.3.0.1:443/api/v1/namespaces/deis/replicationcontrollers/deis-router: x509: certificate is valid for 127.0.0.1, 192.168.64.2, not 10.3.0.1.
```

**Comment by jchauncey** [comment]
That seems to me like its a problem in k8s

**Comment by rimusz** [comment]
yep cert one problem for the kubernetes service IP

**Comment by rimusz** [comment]
k8s API needs to be accessed via endpoint IP from the pod, that should sort the problem

**Comment by krancour** [comment]
Are we cool closing this now?  Seems the issue is in k8s.

**Comment by jchauncey** [comment]
Yes
